# Generated by Django 5.2.1 on 2025-06-02 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Is Featured')),
                ('is_selling', models.BooleanField(default=False, verbose_name='Is Selling')),
                ('is_fact', models.BooleanField(default=False, verbose_name='Is Fact')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Is Popular')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('is_trending', models.BooleanField(default=False, verbose_name='Is Trending')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='status_icon/')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Is Featured')),
                ('is_selling', models.BooleanField(default=False, verbose_name='Is Selling')),
                ('is_fact', models.BooleanField(default=False, verbose_name='Is Fact')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Is Popular')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('is_trending', models.BooleanField(default=False, verbose_name='Is Trending')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_status', to='blog.status')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
