# Generated by Django 5.2.1 on 2025-06-04 14:47

import django.db.models.deletion
import djrichtextfield.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Is Featured')),
                ('is_selling', models.BooleanField(default=False, verbose_name='Is Selling')),
                ('is_fact', models.BooleanField(default=False, verbose_name='Is Fact')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Is Popular')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('is_trending', models.BooleanField(default=False, verbose_name='Is Trending')),
                ('full_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=13)),
                ('image', models.ImageField(upload_to='testimonals_images/')),
                ('message', models.TextField()),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoffeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Is Featured')),
                ('is_selling', models.BooleanField(default=False, verbose_name='Is Selling')),
                ('is_fact', models.BooleanField(default=False, verbose_name='Is Fact')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Is Popular')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('is_trending', models.BooleanField(default=False, verbose_name='Is Trending')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('mini_desc', models.CharField(max_length=200)),
                ('description', djrichtextfield.models.RichTextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='coffee_images/')),
                ('views', models.PositiveIntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('percentage', models.IntegerField(default=0)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coffee_status', to='blog.status')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Is Featured')),
                ('is_selling', models.BooleanField(default=False, verbose_name='Is Selling')),
                ('is_fact', models.BooleanField(default=False, verbose_name='Is Fact')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Is Popular')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('is_trending', models.BooleanField(default=False, verbose_name='Is Trending')),
                ('name', models.CharField(max_length=50)),
                ('humans', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, max_length=5)),
                ('text', models.CharField(max_length=200)),
                ('coffee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coffeess', to='coffee.coffeemodel')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
