# Generated by Django 5.2.1 on 2025-06-12 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_alter_coffeemodel_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeemodel',
            name='mini_desc',
        ),
    ]
