# Generated by Django 5.2.1 on 2025-06-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_remove_coffeemodel_mini_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeemodel',
            name='sub_desc',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
